#!/bin/sh
exec tail -n +3 $0
# This file provides an easy way to add custom menu entries.  Simply type the
# menu entries you want to add after this comment.  Be careful not to change
# the 'exec tail' line above.
menuentry "Clonezilla (Arch Backup)" {
	# load BTRFS driver
	insmod btrfs
	
	# search for the BTRFS root filesystem (so we can load clonezilla iso file from it)
	search --no-floppy --fs-uuid --set ea3e4ee1-8a1f-4a0b-baa7-5001571cd84b
	set isofile="/home/fileserver/Applications/backup/clonezilla.iso"
	loopback loop $isofile
	linux (loop)/live/vmlinuz boot=live union=overlay username=user config components quiet noswap nolocales edd=on nomodeset nodmraid noeject 
	
	# the command to start automatic backup to Media
	ocs_prerun=" mount UUID=96dac97c-a466-449b-aee3-1ffb87ba0cf8 /mnt" ocs_prerun1="mount --bind /mnt/SystemImage /home/partimag/" ocs_live_run="/usr/sbin/ocs-sr --batch -q2 -j2 -z5p -p reboot savedisk Fileserver sda" ocs_live_extra_param="" keyboard-layouts=be2-latin1 timezone=Europe/Brussels ocs_live_batch="yes" locales=en_US.UTF-8 vga=788 ip=frommedia nosplash toram=filesystem.squashfs findiso=$isofile
	initrd (loop)/live/initrd.img

	# After boot, set default again to standard Arch Linux
	savedefault 0
}

menuentry "Clonezilla (interactive)" {
	insmod btrfs
	search --no-floppy --fs-uuid --set ea3e4ee1-8a1f-4a0b-baa7-5001571cd84b
	set isofile="/home/fileserver/Applications/backup/clonezilla.iso"
	loopback loop $isofile
	linux (loop)/live/vmlinuz boot=live union=overlay username=user config components quiet noswap nolocales edd=on nomodeset nodmraid ocs_live_run="ocs-live-general" ocs_live_extra_param="" keyboard-layouts=be2-latin1 timezone=Europe/Brussels ocs_live_batch="no" locales=en_US.UTF-8 vga=788 ip=frommedia nosplash toram=filesystem.squashfs findiso=$isofile
	initrd (loop)/live/initrd.img
	savedefault 0
}

menuentry "Clonezilla (Arch Restore)" {
	insmod btrfs
	search --no-floppy --fs-uuid --set ea3e4ee1-8a1f-4a0b-baa7-5001571cd84b
	set isofile="/home/fileserver/Applications/backup/clonezilla.iso"
	loopback loop $isofile
	linux (loop)/live/vmlinuz boot=live union=overlay username=user config components quiet noswap nolocales edd=on nomodeset nodmraid noeject ocs_prerun=" mount UUID=96dac97c-a466-449b-aee3-1ffb87ba0cf8 /mnt" ocs_prerun1="mount --bind /mnt/SystemImage /home/partimag/" ocs_live_run="/usr/sbin/ocs-sr --batch -p reboot restoredisk Fileserver sda" ocs_live_extra_param="" keyboard-layouts=be2-latin1 timezone=Europe/Brussels ocs_live_batch="yes" locales=en_US.UTF-8 vga=788 ip=frommedia nosplash toram=filesystem.squashfs findiso=$isofile
	initrd (loop)/live/initrd.img
	savedefault 0
}